name = "websites"
compatibility_date = "2026-04-15"

routes = [
  { pattern = "batterycalculators.com/*", zone_name = "batterycalculators.com" }
]

kv_namespaces = [
  { binding = "SESSION", id = "274898773e364b349546eb5c4a69006d" }
]

[assets]
directory = "./dist/client"
not_found_handling = "404-page"
